import numpy as np
numbers = np.array([2,3,4,5,6])
print(numbers)
print(type(numbers))
numbers = np.array([[2,3,4,5,6],[2,3,4,5,7]])
print(numbers)
print(numbers.dtype)
numbers = np.array([[0.2,3,4,5,6],[2,3,4,5,7]])
print(numbers.dtype)
print(numbers.ndim)
print(numbers.shape)
print(numbers.size)
print(numbers.itemsize)
for row in numbers:
    for col in row:
        print(col,end=' ')
    print()
print(np.zeros(5))
print(np.ones((2,4),dtype=int))
print(np.full((3,4),13))
print(np.random.randint(0,9,size=(3,4)))
print(np.arange(5))
numbers2 =  numbers.copy()
numbers3 =  numbers.view()
print(id(numbers))
print(id(numbers2))
print(id(numbers3))
numbers *= 10
print((numbers))
print((numbers2))
print((numbers3))